stages:
  - build
  - push_image
  - deploy

Build:
  stage: build
  tags:
    - shell
  script:
    - docker info
    - docker images
    - docker ps
    - ls
    - docker build -t $IMAGE_URL .
    - docker images

Push Image:
  stage: push_image
  tags:
    - shell
  only:
    - tags
  script:
    - ls
    - cp /home/gitlab-runner/key.json .
    - gcloud version
    - gcloud auth activate-service-account $SA_EMAIL --key-file key.json
    - gcloud config set project $PROJECT_ID
    - gcloud auth configure-docker
    - docker images
    - docker push $IMAGE_URL

Deploy:
  stage: deploy
  tags:
    - shell
  only:
    - tags
  script:
    - ls
    - cp /home/gitlab-runner/key.json .
    - gcloud version
    - cat key.json 
    - gcloud auth activate-service-account $SA_EMAIL --key-file key.json
    - gcloud config set project $PROJECT_ID
    - gcloud run deploy $SERVICE_NAME --image=$IMAGE_URL --port=$PORT --region=$REGION --service-account=$SA_EMAIL --allow-unauthenticated